server:
  port: 8080

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/security
    driver-class-name: org.postgresql.Driver
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  data:
    mongodb:
      uri: mongodb://localhost:27017/ejercicios

